name: pyteaching
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - matplotlib
  - dll
  - partd
  - dask
  - bokeh
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - seaborn
  - scipy
  - zlib
  - libpython

